name: pollora_app
description: A dark-mode social polling app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.9
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  share_plus: ^10.1.4

  # Supabase
  supabase_flutter: ^2.5.0

  # Auth
  google_sign_in: ^6.2.0
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3           # required by sign_in_with_apple nonce

  # Images
  cached_network_image: ^3.3.1
  path: ^1.9.0

  # Config
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
